name: 'Up merge'
description: 'Automatically up merge changes from one branch to another'
author: 'Manuel Christlieb'
branding:
  icon: 'git-merge'
  color: 'orange'
inputs:
  from_branch:
    description: 'Name of the branch to merge from'
    required: false
    default: 'master'
  to_branch:
    description: 'Name of the branch to merge to'
    required: false
    default: 'develop'
  user_name:
    description: 'User name for git commits'
    required: false
    default: 'GitHub Upmerge Action'
  user_email:
    description: 'User email for git commits'
    required: false
    default: 'actions@github.com'
  push_token:
    description: 'Environment variable containing the token to use for push'
    required: false
    default: 'GITHUB_TOKEN'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
